name = "Eudokia"
license = "MIT"
description = "A minimal, latex-style hugo theme for personal blogging"
homepage = "https://github.com/arch-dawson/eudokia-theme"
tags = ["blog", "clean", "latex", "minimal", "simple"]
features = ["blog"]
min_version = "0.60"

[author]
name = "Dawson Beatty"
homepage = "https://github.com/arch-dawson/"
